blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/orgs/InfraTales/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“š Documentation
    url: https://infratales.com/docs
    about: Read our documentation
  - name: ğŸŒ Website
    url: https://infratales.com
    about: Visit our website
